"""
UniPath AI - Configuration
Reads secrets from environment variables. Never hardcode API keys here.

Required env var for live LLM calls:
    GROQ_API_KEY

Optional:
    GROQ_MODEL        (default: llama-3.3-70b-versatile)
    UNIPATH_TOP_K      (default: 4)  -> number of RAG chunks retrieved per query
"""

import os

# --- LLM / Groq settings ---
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "").strip()
GROQ_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# If no API key is set, the module runs in MOCK MODE:
# agents still work end-to-end (retrieval + reasoning templates),
# but the "AI-written" text is generated by a local template
# instead of a real LLM call. This lets your friend run/demo the
# module immediately, then flip to live mode by just setting GROQ_API_KEY.
MOCK_MODE = GROQ_API_KEY == ""

# --- RAG settings ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
KB_DIR = os.path.join(BASE_DIR, "knowledge_base")
TOP_K = int(os.environ.get("UNIPATH_TOP_K", "4"))

# --- Generation settings ---
LLM_TEMPERATURE = 0.3
LLM_MAX_TOKENS = 900
